### ISSUE TITLE
error when run test.py: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by godlovehill** [4uiiurz1/pytorch-nested-unet#11]
hi, i got a error 'CUDNN_STATUS_EXECUTION_FAILED' when run the test.py. Here is my environment: python3.6,  cuda=9.0, cudnn=7.6.5, pytorch=0.4.0. I carefully followed the requirement.txt, but still got this error, any suggestion? Thank you

**Comment by 4uiiurz1** [comment]
@godlovehill 
I don't know what the problem is. Please pull the latest commit and try again.

**Comment by Lizadanyang** [comment]
I can't see the test.py file, can you send me by email?

**Comment by zhouyi-git** [comment]
> hi, i got a error 'CUDNN_STATUS_EXECUTION_FAILED' when run the test.py. Here is my environment: python3.6, cuda=9.0, cudnn=7.6.5, pytorch=0.4.0. I carefully followed the requirement.txt, but still got this error, any suggestion? Thank you

can you give me test.py ？thank you ,1092622009@qq.com
