### ISSUE TITLE
could not get segmented image after running val.py file

### ISSUE THREAD

**Issue by manvirvirk** [4uiiurz1/pytorch-nested-unet#15]
please help

**Comment by 4uiiurz1** [comment]
@manvirvirk Thanks for letting me know. I fixed val.py.

**Comment by manvirvirk** [comment]
Still could not get segmented image after running val.py.

**Comment by 4uiiurz1** [comment]
Sorry, please pull again.

**Comment by manvirvirk** [comment]
could not find it

**Comment by manvirvirk** [comment]
I m facing one more issue of "early stopping". After 10 epoch it stops. Please help

**Comment by manvirvirk** [comment]
the predicted image is gray box. No information is there.
