### ISSUE TITLE
 Please change the validation code.

### ISSUE THREAD

**Issue by tjdalsckd** [4uiiurz1/pytorch-nested-unet#19]
If the code is not modified, the same output file is created.

https://github.com/4uiiurz1/pytorch-nested-unet/blob/1424f72b7ac3816e450a1c596450e3e68e678f4a/val.py#L105

 (output[i, c] * 255).astype('uint8'))

**Comment by 4uiiurz1** [comment]
@tjdalsckd Thanks for letting me know! I fixed it.
