### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by evaldsurtans** [4uiiurz1/pytorch-nested-unet#2]
Nice code, thanks for sharing.

As you did not show results, in your opinion where nested-unet/unet++ stands in precision between standard resnet, densenet, squeezenet etc?

Does it perform much better?

**Comment by 4uiiurz1** [comment]
Sorry for replying so late.
I added the results to README, you should check it.

The author said the reasons of UNet++ working well, "The re-designed skip pathways aim at reducing the semantic gap between the feature maps of the encoder and decoder sub-networks. We argue that the optimizer would deal with an easier learning task when the feature maps from the decoder and encoder networks are semantically similar."
