### ISSUE TITLE
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

### ISSUE THREAD

**Issue by JiyueWang** [4uiiurz1/pytorch-nested-unet#4]
pc:~/unets/pytorch-nested-unet-master$ python train.py --dataset dsb2018_96 --arch NestedUNet
Config -----
name: dsb2018_96_NestedUNet_woDS
arch: NestedUNet
deepsupervision: False
dataset: dsb2018_96
input_channels: 3
image_ext: png
mask_ext: png
aug: False
loss: BCEDiceLoss
epochs: 10000
early_stop: 20
batch_size: 16
optimizer: Adam
lr: 0.0003
momentum: 0.9
weight_decay: 0.0001
nesterov: False
------------
Traceback (most recent call last):
  File "train.py", line 301, in <module>
    main()
  File "train.py", line 222, in main
    train_test_split(img_paths, mask_paths, test_size=0.2, random_state=41)
  File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2100, in train_test_split
    default_test_size=0.25)
  File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 1782, in _validate_shuffle_split
    train_size)
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters

**Comment by JiyueWang** [comment]
Anyone got the same problem?

**Comment by JiyueWang** [comment]
fixed this after change --dataset dsb2018_96 to --dataset dsb2018_256

**Comment by JiyueWang** [comment]
now is the new issue
-pc:~/unets/pytorch-nested-unet-master$ python train.py --dataset dsb2018_256 --arch NestedUNetConfig -----
name: dsb2018_256_NestedUNet_woDS
arch: NestedUNet
deepsupervision: False
dataset: dsb2018_256
input_channels: 3
image_ext: png
mask_ext: png
aug: False
loss: BCEDiceLoss
epochs: 10000
early_stop: 20
batch_size: 16
optimizer: Adam
lr: 0.0003
momentum: 0.9
weight_decay: 0.0001
nesterov: False
------------
=> creating model NestedUNet
9163329
Epoch [0/10000]
  0%|                                                                                                                         | 0/33 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 301, in <module>
    main()
  File "train.py", line 264, in main
    train_log = train(args, train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 118, in train
    for i, (input, target) in tqdm(enumerate(train_loader), total=len(train_loader)):
  File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/tqdm/std.py", line 1091, in __iter__
    for obj in iterable:
  File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 81, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'imageio.core.util.Array'>
  0%|

**Comment by lzw0515** [comment]
> ## now is the new issue
> -pc:~/unets/pytorch-nested-unet-master$ python train.py --dataset dsb2018_256 --arch NestedUNetConfig -----
> name: dsb2018_256_NestedUNet_woDS
> arch: NestedUNet
> deepsupervision: False
> dataset: dsb2018_256
> input_channels: 3
> image_ext: png
> mask_ext: png
> aug: False
> loss: BCEDiceLoss
> epochs: 10000
> early_stop: 20
> batch_size: 16
> optimizer: Adam
> lr: 0.0003
> momentum: 0.9
> weight_decay: 0.0001
> nesterov: False
> => creating model NestedUNet
> 9163329
> Epoch [0/10000]
> 0%| | 0/33 [00:00<?, ?it/s]Traceback (most recent call last):
> File "train.py", line 301, in 
> main()
> File "train.py", line 264, in main
> train_log = train(args, train_loader, model, criterion, optimizer, epoch)
> File "train.py", line 118, in train
> for i, (input, target) in tqdm(enumerate(train_loader), total=len(train_loader)):
> File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/tqdm/std.py", line 1091, in **iter**
> for obj in iterable:
> File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in **next**
> data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
> return self.collate_fn(data)
> File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
> return [default_collate(samples) for samples in transposed]
> File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in 
> return [default_collate(samples) for samples in transposed]
> File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 81, in default_collate
> raise TypeError(default_collate_err_msg_format.format(elem_type))
> TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'imageio.core.util.Array'>
> 0%|

Are you OK? I met the same problem!

**Comment by leeskyed** [comment]
@lzw0515 You need to convert the Image to tensor type in newer version of PyTorch. BTW, you should also remove the relative codes in the dataset file.

**Comment by lloydjie1** [comment]
Hi I got this issue after I changed the glob mask_path to absolute address, anyone got the same problem?
=> creating model NestedUNet
9163329
Epoch [0/10000]
  0%|                                                                                        | 0/6 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 304, in <module>
    main()
  File "train.py", line 267, in main
    train_log = train(args, train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 117, in train
    for i, (input, target) in tqdm(enumerate(train_loader), total=len(train_loader)):
  File "/root/miniconda/envs/pyt3.7/lib/python3.7/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/root/miniconda/envs/pyt3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/miniconda/envs/pyt3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda/envs/pyt3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda/envs/pyt3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/work/pytorch-nested-unet/dataset.py", line 42, in __getitem__
    mask = mask.transpose((2, 0, 1))
ValueError: axes don't match array
  0%|                                                                                        | 0/6 [00:01<?, ?it/s

**Comment by JAY-PANCHAL** [comment]
> Anyone got the same problem?

yes same problem occured couldn't work with both train_size and test_size

**Comment by liaduarte** [comment]
I have the same problem. How can I solve it?

**Comment by Lisongjie1997** [comment]
> Anyone got the same problem?

I have the same problem.How can I fix it?

**Comment by ransisathsarani** [comment]
I got the same error. How can i solve this issue?

**Comment by Deepankar-98** [comment]
I got the same error.  How can i solve it?

df = pd.read_csv('dataset/breast_cancer_wisconsin.csv')
df.replace('?',-99999, inplace=True)
df['class'] = df['diagnosis'].apply(lambda x: 1 if x == 'M' else 0)
df.drop(['id','diagnosis'], 1, inplace=True)
df.dropna( how ='any',inplace=True)
X = np.array(df.drop(['class'], 1))
y = np.array(df['class'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size = 0.8)
clf = svm.SVC()

clf.fit(X_train.reshape((-1, 31)), y_train)
confidence = clf.score(X_test, y_test)
print(confidence)

example_measures = np.array([[4,2,1,1,1,2,3,2,1]])
example_measures = example_measures.reshape(len(example_measures), -1)
prediction = clf.predict(example_measures)
print(prediction)


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-c749aa4356b5> in <module>
      2 y = np.array(df['class'])
      3 
----> 4 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size = 0.8)
      5 clf = svm.SVC()
      6 

F:\InstallationFolder\anaconda\lib\site-packages\sklearn\model_selection\_split.py in train_test_split(*arrays, **options)
   2098     n_samples = _num_samples(arrays[0])
   2099     n_train, n_test = _validate_shuffle_split(n_samples, test_size, train_size,
-> 2100                                               default_test_size=0.25)
   2101 
   2102     if shuffle is False:

F:\InstallationFolder\anaconda\lib\site-packages\sklearn\model_selection\_split.py in _validate_shuffle_split(n_samples, test_size, train_size, default_test_size)
   1780             'resulting train set will be empty. Adjust any of the '
   1781             'aforementioned parameters.'.format(n_samples, test_size,
-> 1782                                                 train_size)
   1783         )
   1784 

ValueError: With n_samples=0, test_size=0.2 and train_size=0.8, the resulting train set will be empty. Adjust any of the aforementioned parameters.
---------------------------------------------------------------------------

**Comment by ssyonline** [comment]
i had same problem, how to solve it?

**Comment by 201814476** [comment]
> ## pc:~/unets/pytorch-nested-unet-master$ python train.py --dataset dsb2018_96 --arch NestedUNet
> Config -----
> name: dsb2018_96_NestedUNet_woDS
> arch: NestedUNet
> deepsupervision: False
> dataset: dsb2018_96
> input_channels: 3
> image_ext: png
> mask_ext: png
> aug: False
> loss: BCEDiceLoss
> epochs: 10000
> early_stop: 20
> batch_size: 16
> optimizer: Adam
> lr: 0.0003
> momentum: 0.9
> weight_decay: 0.0001
> nesterov: False
> 
> Traceback (most recent call last): File "train.py", line 301, in main() File "train.py", line 222, in main train_test_split(img_paths, mask_paths, test_size=0.2, random_state=41) File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2100, in train_test_split default_test_size=0.25) File "/home/jiyue/anaconda3/envs/judy/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 1782, in _validate_shuffle_split train_size) ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters

你好，请问你这个问题是怎么解决的？
