### ISSUE TITLE
Question about "ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters".

### ISSUE THREAD

**Issue by wxyWendy** [4uiiurz1/pytorch-nested-unet#48]
When I use "python train.py --dataset dsb2018_96 --arch NestedUNet" to run the code,why then it turns out"ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters."?

**Comment by wxyWendy** [comment]
I have solved it.

**Comment by meenakshi0910** [comment]
Can you tell how you solved ?because I do have a same error which I cant figure out

**Comment by farazBhatti** [comment]
@meenakshi0910  you need to run python3 preprocess_dsb2018.py to first preprocess your dataset
