### ISSUE TITLE
error: NameError: name 'joblib' is not defined

### ISSUE THREAD

**Issue by manvirvirk** [4uiiurz1/pytorch-nested-unet#6]
File "train.py", line 300, in <module>
    main()
  File "train.py", line 206, in main
    joblib.dump(args, 'models/%s/args.pkl' %args.name)
NameError: name 'joblib' is not defined
i m getting above error?

**Comment by Hwan6316** [comment]
I solved this by adding

import joblib as joblib

**Comment by KL-Ding** [comment]
> File "train.py", line 300, in 
> main()
> File "train.py", line 206, in main
> joblib.dump(args, 'models/%s/args.pkl' %args.name)
> NameError: name 'joblib' is not defined
> i m getting above error?

i met same error

**Comment by manvirvirk** [comment]
could you solve it?

**Comment by 4uiiurz1** [comment]
@manvirvirk @Hwan6316 @KL-Ding 
Sorry for the delay in replying. It should be fixed in the latest commit. Please let me know if it's not fixed.

**Comment by manvirvirk** [comment]
no it is not fixed

**Comment by 4uiiurz1** [comment]
@manvirvirk 
In the latest commits, joblib is not used. So please pull and try again.

**Comment by Joshluk3328j** [comment]
if you are using Jupyter notebook, try running the previous cells first before you run the joblib cell.
